### ISSUE TITLE
Warning on builder 3.0.2

### ISSUE THREAD

**Issue by asanghi** [jimweirich/builder#28]
Just updated builder to version 3.0.2 (3.1.0 is locked out from rails 3.2.8)

I'm seeing the following warning:

``` text
/snip/ruby-1.9.3-p194/gems/builder-3.0.2/lib/blankslate.rb:51: warning: undefining `object_id' may cause serious problems
```

**Comment by jimweirich** [comment]
Suppressed the warning on removing object_id in BlankSlate in version 3.0.3.  

FYI: Technically, builder does not use BlankSlate in Ruby 1.9 (it uses the built-in BasicObject), so it must be some third party library pulling it in.
