### ISSUE TITLE
Nested cdata in cdata! should raise exceptions 

### ISSUE THREAD

**Issue by CloCkWeRX** [jimweirich/builder#31]
The XML specs don't allow nested cdata, so anything passed to Builder::XmlMarkup::cdata! should probably raise an exception.

See https://github.com/sj26/rspec_junit_formatter/issues/5

**Comment by sj26** [comment]
This is already fixed in 3.1.1 by escaping cdata: https://github.com/jimweirich/builder/compare/builder-3.0.0...builder-3.1.1#L9L264

**Comment by CloCkWeRX** [comment]
Ah.
