### ISSUE TITLE
Add option to make xml.tag! handle nil values like rails ActiveRecord::Base#to_xml

### ISSUE THREAD

**Issue by hderms** [jimweirich/builder#33]
Nil values are handled differently in this gem versus rendering in the rails controller like:

``` ruby
render xml: @object
```

I think it would be nice if there was some way of instructing Builder to do something similar. More specifically, instead of a tag (foo) with a nil value being rendered like 

``` xml
<foo />
```

We could get something like:

``` xml
<foo nil="true"/>
```

Having the option of representing nil values explicitly, without the user having to do the checks themselves would be nice.

**Comment by jimweirich** [comment]
Resolved in issue #34.
