### ISSUE TITLE
In lib/builder/xmlmarkup.rb sometimes Symbol/Hash etc. are not available

### ISSUE THREAD

**Issue by johnae** [jimweirich/builder#4]
I'm not sure if this is because of the usage of BlankSlate but if changing for example this line in lib/builder/xmlmarkup.rb:

sym = "#{sym}:#{args.shift}" if args.first.kind_of?(Symbol)

to

sym = "#{sym}:#{args.shift}" if args.first.kind_of?(::Symbol)

everything works ok. It's difficult to say exactly when this happens, but the fix is to reference the objects prepended with :: (for top level I guess). Otherwise I just get: lib/builder/xmlbase.rb:40:in `method_missing': uninitialized constant Builder::XmlBase::Symbol (NameError).

**Comment by johnae** [comment]
This is on Mac OS X 10.6.5 using rvm, ruby version is: ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0]

haven't tried any other ruby versions yet, but I've seen this error mentioned a few times before (when googling for it) - no solutions though.

**Comment by skrat** [comment]
I can confirm that this makes builder Ruby 1.9.2 incompatible.

**Comment by johnae** [comment]
Ok so, nothing new on this? This actually seem to be a conflict between amqp-gem and builder 2.1.2 (on which alot of stuff depends).

**Comment by michaelklishin** [comment]
I am sorry but how does it have anything to do with amqp gem? It is a constant name resolution issue inside builder. amqp gem does not monkey patch anything and uses method_missing on just one class. It also has no classes named Symbol.

**Comment by johnae** [comment]
Yes I know. I don't know for sure where this error comes from but this code works:

```
require 'rubygems'
#require 'mq'
require 'rails'
require 'builder'

builder = Builder::XmlMarkup.new
xml = builder.person { |b| b.name("Jim"); b.phone("555-1234") }
puts xml
```

and this does NOT work:

```
require 'rubygems'
require 'mq'
require 'rails'
require 'builder'

builder = Builder::XmlMarkup.new
xml = builder.person { |b| b.name("Jim"); b.phone("555-1234") }
puts xml
```

the only difference here is that it doesn't work when including 'mq'. Don't know if the actual problem is in builder though, but the problem only manifests when including 'mq'.

The problem also only manifests when running builder 2.1.2 (on which Rails among many other gems depends).

**Comment by johnae** [comment]
Please see: https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/5985

Don't know why rails 3.0.5 (latest as of now) still depend on builder 2.1.2.

**Comment by michaelklishin** [comment]
And indeed it was an amqp gem problem. This issue can be closed.

**Comment by jimweirich** [comment]
So closed
