### ISSUE TITLE
Doc and license files missing in the distributed .gem

### ISSUE THREAD

**Issue by strzibny** [jimweirich/builder#43]
Hi,

in the last release (3.2.0) I cannot find the doc files, nor the new MIT license file. Is there a good reason to exclude those? Could you please at least keep the license file? When we package builder for Fedora we need to include the license file, so it's much easier if it comes along.

Thank you.

**Comment by jimweirich** [comment]
Good catch.  Thanks for the heads up.

Fixed in head and pushed as version 3.2.1.
